"""
Inserta la sección 'Efecto Gaviota' en el notebook 00_master.
Posición: entre celda 21 (recuperación) y celda 22 (## 9 Inferencia).
"""
import json
from pathlib import Path

BASE = next(p for p in Path(__file__).resolve().parents if (p / "07_Config").is_dir())  # raiz del repo (portable)
NB   = BASE / 'notebooks' / '00_master_analisis_rendimientos_t8.ipynb'

def md(src):  return {"cell_type":"markdown","id":f"gm{abs(hash(src))%999999:06d}","metadata":{},"source":src}
def code(src): return {"cell_type":"code","execution_count":None,"id":f"gc{abs(hash(src))%999999:06d}","metadata":{},"outputs":[],"source":src}

# ─── Skills audit ────────────────────────────────────────────────────────────
C_SKILLS = code(
"# ── Gobernanza: Skills aplicados a esta sección ─────────────────────────\n"
"import json, logging\n"
"from datetime import datetime\n"
"logging.getLogger('matplotlib').setLevel(logging.WARNING)\n\n"
"SKILLS_GAVIOTA = [\n"
"    'skill_molienda_sag',\n"
"    'skill_operaciones_mina_subterranea',\n"
"    'skill_series_temporales_industriales',\n"
"    'skill_data_scientist_senior',\n"
"    'skill_data_quality_governance',\n"
"]\n"
"print('Skills aplicados — Monitoreo Efecto Gaviota:')\n"
"for s in SKILLS_GAVIOTA: print(f'  + {s}')\n\n"
"with open(LOGS_DIR/'skill_audit.log','a',encoding='utf-8') as f:\n"
"    f.write(json.dumps({'fecha':datetime.now().isoformat(),\n"
"        'seccion':'MonitoreoEfectoGaviota','skills':SKILLS_GAVIOTA},\n"
"        ensure_ascii=False)+'\\n')\n\n"
"# ── Parámetros configurables ─────────────────────────────────────────────\n"
"PRE_HOURS     = 24     # horas antes de la ventana\n"
"POST_HOURS    = 24     # horas después de la ventana\n"
"ROLLING_WIND  = '1h'   # ventana de media móvil\n"
"MIN_PRE_PTS   = 50     # mínimo de puntos 5-min en pre para calcular métricas\n"
"TOP_EVENTOS   = 8      # máximo de eventos individuales a graficar\n"
"IMPACTO_UMBS  = {'Sin impacto':-5,'Leve':-10,'Medio':-20}  # pct umbrales\n\n"
"OUT_GAV = OUT_FIG / 'efecto_gaviota'\n"
"OUT_GAV.mkdir(exist_ok=True)\n"
"print(f'Parámetros: PRE={PRE_HOURS}h | POST={POST_HOURS}h | Rolling={ROLLING_WIND}')"
)

# ─── Funciones reutilizables ─────────────────────────────────────────────────
C_FUNCS = code(
"# ── Funciones reutilizables ──────────────────────────────────────────────\n\n"
"def load_master_dataset():\n"
"    \"\"\"Retorna copia del dataset maestro ya cargado.\"\"\"\n"
"    return df_master.copy()\n\n"
"def get_t8_events(dm=None, min_horas=0):\n"
"    \"\"\"Detecta ventanas T8 continuas. Retorna lista de dicts {ini, fin, horas_total}.\"\"\"\n"
"    dm = dm if dm is not None else df_master\n"
"    dias = dm[dm['horas_t8'] > min_horas].sort_values('fecha')\n"
"    if dias.empty: return []\n"
"    evs = []; s = e = dias.iloc[0]['fecha']\n"
"    for _, row in dias.iloc[1:].iterrows():\n"
"        if (row['fecha'] - e).days <= 2:\n"
"            e = row['fecha']\n"
"        else:\n"
"            mask = (dm['fecha']>=s)&(dm['fecha']<=e)\n"
"            evs.append({'ini':s,'fin':e+pd.Timedelta(days=1),\n"
"                        'horas_total':dm[mask]['horas_t8'].sum(),\n"
"                        'n_dias':int(mask.sum())})\n"
"            s = e = row['fecha']\n"
"    mask = (dm['fecha']>=s)&(dm['fecha']<=e)\n"
"    evs.append({'ini':s,'fin':e+pd.Timedelta(days=1),\n"
"                'horas_total':dm[mask]['horas_t8'].sum(),'n_dias':int(mask.sum())})\n"
"    return evs\n\n"
"def build_event_window(ev, pre_h=PRE_HOURS, post_h=POST_HOURS):\n"
"    \"\"\"Extrae ventana temporal pre/durante/post de df_rend (5-min).\"\"\"\n"
"    ini, fin = ev['ini'], ev['fin']\n"
"    t0 = ini - pd.Timedelta(hours=pre_h)\n"
"    t1 = fin + pd.Timedelta(hours=post_h)\n"
"    mask = (df_rend['fecha'] >= t0) & (df_rend['fecha'] <= t1)\n"
"    df_w = df_rend[mask].copy()\n"
"    df_w['fase'] = 'pre'\n"
"    df_w.loc[(df_w['fecha']>=ini)&(df_w['fecha']<fin),'fase'] = 'durante'\n"
"    df_w.loc[df_w['fecha']>=fin,'fase'] = 'post'\n"
"    df_w['t_rel_h'] = (df_w['fecha'] - ini).dt.total_seconds() / 3600\n"
"    return df_w\n\n"
"def calculate_pre_post_metrics(df_w, activo, ini, fin):\n"
"    \"\"\"Calcula métricas pre/post para un activo en una ventana de evento.\"\"\"\n"
"    col, op = f'{activo}_tph', f'{activo}_operando'\n"
"    pre  = df_w.loc[(df_w['fase']=='pre')  & df_w[op], col]\n"
"    post = df_w.loc[(df_w['fase']=='post') & df_w[op], col]\n"
"    dur  = df_w.loc[(df_w['fase']=='durante') & df_w[op], col]\n"
"    if len(pre) < MIN_PRE_PTS: return None\n"
"    tph_pre  = pre.mean(); tph_post = post.mean() if len(post)>0 else np.nan\n"
"    tph_dur  = dur.mean() if len(dur)>0 else np.nan\n"
"    delta    = tph_post - tph_pre\n"
"    delta_pct= delta / tph_pre * 100 if tph_pre > 0 else np.nan\n"
"    # TPH mínimo post y su hora\n"
"    post_s = df_w.loc[df_w['fase']=='post', col]\n"
"    roll_post = post_s.rolling(12, min_periods=4).mean()\n"
"    tph_min = roll_post.min(); hora_min = np.nan\n"
"    if not pd.isna(tph_min) and not roll_post.empty:\n"
"        idx_min = roll_post.idxmin()\n"
"        hora_min = df_w.loc[idx_min,'t_rel_h'] if idx_min in df_w.index else np.nan\n"
"    # Tiempo de recuperación\n"
"    def t_rec(pct):\n"
"        thr = tph_pre * pct\n"
"        post_op = df_w.loc[(df_w['fase']=='post')&df_w[op], col].rolling(12,min_periods=4).mean()\n"
"        ok = post_op[post_op >= thr]\n"
"        if ok.empty: return np.nan\n"
"        return df_w.loc[ok.index[0],'t_rel_h']\n"
"    # Toneladas\n"
"    ton_pre  = df_w.loc[df_w['fase']=='pre',  f'{activo}_ton'].sum()\n"
"    ton_post = df_w.loc[df_w['fase']=='post', f'{activo}_ton'].sum()\n"
"    return {\n"
"        'activo':activo,'ini':ini.date(),'fin':fin.date(),\n"
"        'tph_pre':round(tph_pre,1),'tph_durante':round(tph_dur,1) if not np.isnan(tph_dur) else np.nan,\n"
"        'tph_post':round(tph_post,1) if not np.isnan(tph_post) else np.nan,\n"
"        'delta_tph':round(delta,1) if not np.isnan(delta) else np.nan,\n"
"        'delta_pct':round(delta_pct,2) if not np.isnan(delta_pct) else np.nan,\n"
"        'tph_min_post':round(tph_min,1),'hora_tph_min_post':round(hora_min,1),\n"
"        'h_rec_90':round(t_rec(0.90),1),'h_rec_95':round(t_rec(0.95),1),\n"
"        'ton_pre':round(ton_pre,0),'ton_post':round(ton_post,0),\n"
"        'delta_ton':round(ton_post-ton_pre,0),\n"
"    }\n\n"
"def classify_impact(delta_pct):\n"
"    \"\"\"Clasifica impacto según caída porcentual.\"\"\"\n"
"    if pd.isna(delta_pct) or delta_pct >= -5:  return 'Sin impacto'\n"
"    if delta_pct >= -10: return 'Leve'\n"
"    if delta_pct >= -20: return 'Medio'\n"
"    return 'Alto'\n\n"
"print('Funciones cargadas: load_master_dataset | get_t8_events | build_event_window')\n"
"print('                    calculate_pre_post_metrics | classify_impact')"
)

# ─── Detección de eventos + métricas ─────────────────────────────────────────
C_EVENTS = code(
"# ── Detectar eventos y calcular métricas ─────────────────────────────────\n"
"eventos_t8 = get_t8_events()\n"
"print(f'Eventos T8 detectados: {len(eventos_t8)}')\n"
"for v in eventos_t8[:5]:\n"
"    print(f'  {v[\"ini\"].date()} → {v[\"fin\"].date()} | {v[\"horas_total\"]:.0f}h acumuladas | {v[\"n_dias\"]} días')\n\n"
"metricas_todas = []\n"
"for ev in eventos_t8:\n"
"    df_w = build_event_window(ev)\n"
"    if df_w.empty: continue\n"
"    for a in ACTIVOS:\n"
"        m = calculate_pre_post_metrics(df_w, a, ev['ini'], ev['fin'])\n"
"        if m:\n"
"            m['horas_t8_evento'] = ev['horas_total']\n"
"            m['impacto'] = classify_impact(m['delta_pct'])\n"
"            metricas_todas.append(m)\n\n"
"df_met = pd.DataFrame(metricas_todas)\n"
"print(f'\\nMétricas calculadas: {len(df_met)} registros ({len(eventos_t8)} eventos × {len(ACTIVOS)} activos)')\n\n"
"# Resumen por activo\n"
"resumen_activo = df_met.groupby('activo').agg(\n"
"    eventos=('ini','count'),\n"
"    delta_pct_medio=('delta_pct','mean'),\n"
"    delta_pct_min=('delta_pct','min'),\n"
"    h_rec90_medio=('h_rec_90','mean'),\n"
"    h_rec95_medio=('h_rec_95','mean'),\n"
"    pct_sin_impacto=('impacto',lambda x:(x=='Sin impacto').mean()*100),\n"
"    pct_alto=('impacto',lambda x:(x=='Alto').mean()*100),\n"
").round(2)\n"
"print('\\nResumen por activo:')\n"
"display(resumen_activo)\n\n"
"# Distribución de impacto\n"
"print('\\nDistribución de clasificación de impacto:')\n"
"pivot_imp = df_met.pivot_table(index='impacto',columns='activo',values='ini',\n"
"                                aggfunc='count',fill_value=0)\n"
"display(pivot_imp)"
)

# ─── Plot por evento ──────────────────────────────────────────────────────────
C_PLOT_EV = code(
"# ── Gráficos por evento (Top eventos por impacto) ────────────────────────\n"
"def plot_event_timeseries(ev, ax_row, titulo=''):\n"
"    \"\"\"Grafica pre/durante/post para los 4 activos en una fila de ejes.\"\"\"\n"
"    df_w = build_event_window(ev)\n"
"    if df_w.empty: return\n"
"    ini, fin = ev['ini'], ev['fin']\n"
"    for ax, a in zip(ax_row, ACTIVOS):\n"
"        col = f'{a}_tph'\n"
"        s = df_w.set_index('fecha')[col]\n"
"        roll = s.rolling(ROLLING_WIND, min_periods=4).mean()\n"
"        # Pre-promedio\n"
"        pre_mask = df_w['fase']=='pre'\n"
"        post_mask = df_w['fase']=='post'\n"
"        tph_pre  = df_w.loc[pre_mask  & df_w[f'{a}_operando'], col].mean()\n"
"        tph_post = df_w.loc[post_mask & df_w[f'{a}_operando'], col].mean()\n"
"        # Datos\n"
"        ax.fill_between(s.index, s.values, alpha=0.2, color=COLORES[a])\n"
"        ax.plot(roll.index, roll.values, color=COLORES[a], linewidth=1.5, label='MA 1h')\n"
"        # Zona ventana T8\n"
"        ax.axvspan(ini, fin, alpha=0.18, color='red', label='T8')\n"
"        ax.axvline(ini, color='red',   linewidth=1.5, linestyle='--')\n"
"        ax.axvline(fin, color='green', linewidth=1.5, linestyle='--')\n"
"        # Líneas de promedio pre/post\n"
"        pre_end  = df_w.loc[pre_mask,  'fecha'].max()\n"
"        post_ini = df_w.loc[post_mask, 'fecha'].min()\n"
"        post_end = df_w.loc[post_mask, 'fecha'].max()\n"
"        if not pd.isna(tph_pre):\n"
"            ax.hlines(tph_pre, df_w['fecha'].min(), pre_end,\n"
"                      colors='steelblue', linewidths=1.2, linestyles=':', label=f'Pre {tph_pre:.0f}')\n"
"        if not pd.isna(tph_post):\n"
"            ax.hlines(tph_post, post_ini, post_end,\n"
"                      colors='seagreen', linewidths=1.2, linestyles=':', label=f'Post {tph_post:.0f}')\n"
"        delta_pct = (tph_post-tph_pre)/tph_pre*100 if (not pd.isna(tph_pre) and tph_pre>0 and not pd.isna(tph_post)) else np.nan\n"
"        ax.set_title(f'{a}  Δ={delta_pct:+.1f}%' if not np.isnan(delta_pct) else a, fontsize=9)\n"
"        ax.set_ylabel('TPH', fontsize=8); ax.grid(True, alpha=0.25)\n"
"        ax.xaxis.set_major_formatter(mdates.DateFormatter('%d/%m %Hh'))\n"
"        ax.tick_params(axis='x', labelsize=7, rotation=30)\n"
"        ax.legend(fontsize=7, loc='lower right')\n\n"
"# Top eventos por impacto absoluto\n"
"if not df_met.empty:\n"
"    top_evs_ini = (\n"
"        df_met.groupby('ini')['delta_pct'].mean()\n"
"        .sort_values().head(TOP_EVENTOS).index.tolist()\n"
"    )\n"
"    top_evs = [ev for ev in eventos_t8 if ev['ini'].date() in top_evs_ini\n"
"               or str(ev['ini'].date()) in [str(x) for x in top_evs_ini]]\n"
"    top_evs = top_evs[:TOP_EVENTOS]\n"
"else:\n"
"    top_evs = eventos_t8[:TOP_EVENTOS]\n\n"
"print(f'Graficando {len(top_evs)} eventos con mayor impacto...')\n"
"for ev in top_evs:\n"
"    fig, axes = plt.subplots(1, 4, figsize=(18, 4), sharey=False)\n"
"    dur_h = (ev['fin']-ev['ini']).total_seconds()/3600\n"
"    fig.suptitle(\n"
"        f\"Evento T8: {ev['ini'].date()} → {ev['fin'].date()} \"\n"
"        f\"({dur_h:.0f}h) | {ev['horas_total']:.0f}h acum.\",\n"
"        fontsize=11\n"
"    )\n"
"    plot_event_timeseries(ev, axes)\n"
"    plt.tight_layout()\n"
"    fname = f\"ev_{ev['ini'].date()}.png\"\n"
"    plt.savefig(OUT_GAV/fname, bbox_inches='tight', dpi=110)\n"
"    plt.show()\n"
"    plt.close()\n"
"print(f'Figuras guardadas en {OUT_GAV}/')"
)

# ─── Efecto Gaviota agregado ──────────────────────────────────────────────────
C_GAVIOTA = code(
"# ── Gráfico Efecto Gaviota — promedio alineado en t=0 ───────────────────\n"
"def plot_seagull_effect(eventos, activos, pre_h=PRE_HOURS, post_h=POST_HOURS,\n"
"                         rolling=ROLLING_WIND):\n"
"    \"\"\"Alinea todas las ventanas en t=0 y grafica TPH normalizado promedio.\"\"\"\n"
"    N_BINS = int((pre_h + post_h) * 60 / 5)  # bins de 5 min\n"
"    t_eje  = np.linspace(-pre_h, post_h, N_BINS)\n\n"
"    fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n"
"    fig.suptitle(\n"
"        'Efecto Gaviota — TPH Normalizado por Ventana T8\\n'\n"
"        '(1.0 = baseline pre-ventana | zona roja = ventana activa)',\n"
"        fontsize=12\n"
"    )\n"
"    COLORES_FASE = {'pre':'steelblue','durante':'tomato','post':'seagreen'}\n\n"
"    gaviota_data = {}\n"
"    for ax, a in zip(axes.flat, activos):\n"
"        col, op = f'{a}_tph', f'{a}_operando'\n"
"        series_norm = []\n"
"        for ev in eventos:\n"
"            df_w = build_event_window(ev, pre_h, post_h)\n"
"            if df_w.empty: continue\n"
"            pre_vals = df_w.loc[(df_w['fase']=='pre')&df_w[op], col]\n"
"            if len(pre_vals) < MIN_PRE_PTS: continue\n"
"            base = pre_vals.mean()\n"
"            if base < TPH_OPERATIONAL: continue\n"
"            # Resamplear a 5-min uniformes por t_rel_h\n"
"            df_w2 = df_w[['t_rel_h', col]].copy().set_index('t_rel_h')\n"
"            df_interp = df_w2.reindex(\n"
"                df_w2.index.union(t_eje)\n"
"            ).interpolate(method='index')[col].reindex(t_eje)\n"
"            series_norm.append(df_interp.values / base)\n\n"
"        if not series_norm:\n"
"            ax.axis('off'); continue\n"
"        mat = np.array(series_norm)  # (n_eventos, N_BINS)\n"
"        med = np.nanmedian(mat, axis=0)\n"
"        p25 = np.nanpercentile(mat, 25, axis=0)\n"
"        p75 = np.nanpercentile(mat, 75, axis=0)\n"
"        gaviota_data[a] = {'t':t_eje,'med':med,'p25':p25,'p75':p75,'n':len(series_norm)}\n\n"
"        # Plot\n"
"        ax.fill_between(t_eje, p25, p75, alpha=0.25, color=COLORES[a], label='IQR 25-75')\n"
"        ax.plot(t_eje, med, color=COLORES[a], linewidth=2.5, label=f'Mediana (n={len(series_norm)})')\n"
"        ax.axvspan(0, 0, alpha=0)  # dummy\n"
"        # Zona ventana (0 a fin promedio)\n"
"        dur_media = np.mean([(ev['fin']-ev['ini']).total_seconds()/3600 for ev in eventos])\n"
"        ax.axvspan(0, min(dur_media, post_h), alpha=0.15, color='red', label='Zona T8')\n"
"        ax.axvline(0,          color='red',   linewidth=1.5, linestyle='--', label='Inicio T8')\n"
"        ax.axvline(dur_media,  color='orange',linewidth=1.2, linestyle=':', label=f'Fin T8 prom ({dur_media:.0f}h)')\n"
"        ax.axhline(1.0, color='gray', linewidth=0.8, linestyle='-', alpha=0.6)\n"
"        ax.axhline(0.9, color='gray', linewidth=0.6, linestyle=':', alpha=0.5, label='90% baseline')\n"
"        ax.set_title(f'{a}', fontsize=10)\n"
"        ax.set_xlabel('Horas relativas al inicio de T8', fontsize=9)\n"
"        ax.set_ylabel('TPH / TPH baseline', fontsize=9)\n"
"        ax.set_xlim(-pre_h, post_h)\n"
"        ax.set_ylim(bottom=0)\n"
"        ax.legend(fontsize=7, loc='lower right')\n"
"        ax.grid(True, alpha=0.25)\n"
"        # Anotar mínimo\n"
"        idx_min = np.nanargmin(med)\n"
"        ax.annotate(f'Min: {med[idx_min]:.2f}\\n({t_eje[idx_min]:.0f}h)',\n"
"                    xy=(t_eje[idx_min], med[idx_min]),\n"
"                    xytext=(t_eje[idx_min]+3, med[idx_min]-0.05),\n"
"                    fontsize=8, color='red',\n"
"                    arrowprops=dict(arrowstyle='->', color='red', lw=1))\n"
"    plt.tight_layout()\n"
"    plt.savefig(OUT_GAV/'00_Efecto_Gaviota_Agregado.png', bbox_inches='tight', dpi=120)\n"
"    plt.show()\n"
"    return gaviota_data\n\n"
"print('Generando gráfico Efecto Gaviota agregado...')\n"
"gaviota_data = plot_seagull_effect(eventos_t8, ACTIVOS)\n"
"print('Guardado: outputs/figures/efecto_gaviota/00_Efecto_Gaviota_Agregado.png')"
)

# ─── Ranking + tabla resumen ──────────────────────────────────────────────────
C_RANK = code(
"# ── Ranking de impacto + tabla resumen ───────────────────────────────────\n\n"
"# Ranking por peor evento\n"
"df_rank = (\n"
"    df_met[df_met['delta_pct'].notna()]\n"
"    .sort_values('delta_pct')\n"
"    [['activo','ini','fin','horas_t8_evento','delta_pct','tph_pre',\n"
"      'tph_post','h_rec_90','h_rec_95','impacto']]\n"
"    .head(15)\n"
"    .reset_index(drop=True)\n"
")\n"
"df_rank.index += 1\n"
"print('Top 15 eventos con mayor impacto negativo:')\n"
"display(df_rank.round(2))\n\n"
"# Heatmap de impacto por activo y mes\n"
"if not df_met.empty:\n"
"    df_met2 = df_met.copy()\n"
"    df_met2['mes'] = pd.to_datetime(df_met2['ini']).dt.strftime('%Y-%m')\n"
"    pivot_heat = df_met2.pivot_table(\n"
"        values='delta_pct', index='mes', columns='activo',\n"
"        aggfunc='mean'\n"
"    )\n"
"    fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n"
"    # Heatmap delta%\n"
"    if not pivot_heat.empty:\n"
"        sns.heatmap(pivot_heat, ax=axes[0], cmap='RdYlGn', center=0,\n"
"                    annot=True, fmt='.1f', cbar_kws={'label':'Δ% TPH post vs pre'},\n"
"                    linewidths=0.4)\n"
"        axes[0].set_title('Δ% TPH Post vs Pre — por mes y activo'); axes[0].set_ylabel('Mes')\n"
"    # Barras: delta_pct medio por activo\n"
"    met_act = df_met.groupby('activo')['delta_pct'].mean().sort_values()\n"
"    colors_bar = ['tomato' if v<-10 else 'orange' if v<-5 else 'steelblue' for v in met_act]\n"
"    axes[1].barh(met_act.index, met_act.values, color=colors_bar, alpha=0.85)\n"
"    axes[1].axvline(0, color='black', linewidth=0.8)\n"
"    axes[1].axvline(-5,  color='orange', linewidth=1, linestyle='--', alpha=0.6, label='-5% umbral leve')\n"
"    axes[1].axvline(-10, color='tomato', linewidth=1, linestyle='--', alpha=0.6, label='-10% umbral medio')\n"
"    for i, (a, v) in enumerate(met_act.items()):\n"
"        axes[1].text(v-0.3, i, f'{v:.1f}%', va='center', ha='right', fontsize=9)\n"
"    axes[1].set_title('Δ% TPH medio Post vs Pre por Activo'); axes[1].set_xlabel('Δ% TPH')\n"
"    axes[1].legend(fontsize=8); axes[1].grid(True, alpha=0.25, axis='x')\n"
"    plt.tight_layout()\n"
"    plt.savefig(OUT_GAV/'01_Ranking_Impacto.png', bbox_inches='tight', dpi=120)\n"
"    plt.show()\n\n"
"# Recuperación comparativa\n"
"rec_comp = df_met.groupby('activo')[['h_rec_90','h_rec_95']].mean().round(1).sort_values('h_rec_90')\n"
"fig, ax = plt.subplots(figsize=(10,5))\n"
"x = np.arange(len(rec_comp))\n"
"w = 0.35\n"
"ax.bar(x-w/2, rec_comp['h_rec_90'], width=w, label='h hasta 90%', color='steelblue', alpha=0.8)\n"
"ax.bar(x+w/2, rec_comp['h_rec_95'], width=w, label='h hasta 95%', color='seagreen',  alpha=0.8)\n"
"ax.set_xticks(x); ax.set_xticklabels(rec_comp.index)\n"
"ax.set_title('Tiempo de recuperación promedio post-ventana T8'); ax.set_ylabel('Horas')\n"
"ax.legend(); ax.grid(True, alpha=0.3, axis='y')\n"
"plt.tight_layout()\n"
"plt.savefig(OUT_GAV/'02_Recuperacion_Comparativa.png', bbox_inches='tight', dpi=120)\n"
"plt.show()\n"
"print('Graficos guardados en outputs/figures/efecto_gaviota/')"
)

# ─── Export Excel ────────────────────────────────────────────────────────────
C_EXPORT = code(
"# ── Exportar a Excel ─────────────────────────────────────────────────────\n"
"def export_monitoring_outputs(df_met, resumen_activo, df_rank):\n"
"    xls_path = OUT_XLS / 'monitoreo_pre_post_t8.xlsx'\n"
"    with pd.ExcelWriter(xls_path, engine='openpyxl') as wr:\n"
"        # resumen_eventos\n"
"        df_met.round(2).to_excel(wr, sheet_name='resumen_eventos', index=False)\n"
"        # metricas_por_activo\n"
"        resumen_activo.to_excel(wr, sheet_name='metricas_por_activo')\n"
"        # ranking_impacto\n"
"        df_rank.to_excel(wr, sheet_name='ranking_impacto')\n"
"        # recuperacion\n"
"        rec_tab = df_met.groupby('activo')[['h_rec_90','h_rec_95','tph_min_post','hora_tph_min_post']].mean().round(2)\n"
"        rec_tab.to_excel(wr, sheet_name='recuperacion')\n"
"        # gaviota — estadisticas\n"
"        if gaviota_data:\n"
"            gav_rows = []\n"
"            for a, d in gaviota_data.items():\n"
"                gav_rows.append({'activo':a,'n_eventos':d['n'],\n"
"                    'tph_norm_min':round(np.nanmin(d['med']),3),\n"
"                    'h_tph_min':round(d['t'][np.nanargmin(d['med'])],1),\n"
"                    'tph_norm_post_24h':round(d['med'][-1],3)})\n"
"            pd.DataFrame(gav_rows).to_excel(wr, sheet_name='efecto_gaviota', index=False)\n"
"    print(f'Excel guardado: {xls_path}')\n\n"
"export_monitoring_outputs(df_met, resumen_activo, df_rank)"
)

# ─── Resumen ejecutivo ────────────────────────────────────────────────────────
C_SUMMARY = code(
"# ── Resumen ejecutivo automático ─────────────────────────────────────────\n"
"from IPython.display import Markdown, display as ipy_display\n\n"
"def build_executive_summary(df_met, resumen_activo, gaviota_data, eventos_t8):\n"
"    if df_met.empty: return 'Sin datos suficientes para generar resumen.'\n"
"    n_ev = len(eventos_t8)\n"
"    # 1. Mayor caída\n"
"    worst = df_met.loc[df_met['delta_pct'].idxmin()]\n"
"    worst_a = resumen_activo['delta_pct_medio'].idxmin()\n"
"    worst_delta = resumen_activo.loc[worst_a,'delta_pct_medio']\n"
"    # 2. Recuperación más lenta\n"
"    slow_a = resumen_activo['h_rec90_medio'].idxmax()\n"
"    slow_h = resumen_activo.loc[slow_a,'h_rec90_medio']\n"
"    # 3. Gaviota — ¿existe?\n"
"    gav_evidence = []\n"
"    for a, d in gaviota_data.items():\n"
"        idx_0 = np.argmin(np.abs(d['t']))          # t≈0\n"
"        idx_min = np.nanargmin(d['med'])\n"
"        idx_end = -1\n"
"        caida  = d['med'][idx_0] - d['med'][idx_min]\n"
"        recup  = d['med'][idx_end] - d['med'][idx_min]\n"
"        if caida > 0.03 and recup > 0.01:\n"
"            gav_evidence.append(f'{a} (caída={caida:.2f}, recuperación={recup:.2f})')\n"
"    # 4. Eventos críticos (alto impacto)\n"
"    n_criticos = (df_met['impacto']=='Alto').sum()\n"
"    ev_critico = df_met[df_met['impacto']=='Alto'].sort_values('delta_pct').head(1)\n"
"    critico_str = ''\n"
"    if not ev_critico.empty:\n"
"        r = ev_critico.iloc[0]\n"
"        critico_str = f\"{r['activo']} el {r['ini']} (Δ={r['delta_pct']:.1f}%)\"\n\n"
"    md_text = f'''\n"
"## Resumen de Monitoreo Efecto Gaviota — Ventanas T8\n\n"
"| Item | Resultado |\n"
"|------|-----------|\n"
"| Ventanas T8 analizadas | **{n_ev}** |\n"
"| Activo con mayor caída promedio | **{worst_a}** ({worst_delta:.1f}% promedio) |\n"
"| Activo con recuperación más lenta | **{slow_a}** ({slow_h:.1f} h hasta 90%) |\n"
"| Eventos de impacto alto | **{n_criticos}** |\n"
"| Mayor evento crítico | {critico_str or \"N/D\"} |\n"
"| Evidencia efecto gaviota | {', '.join(gav_evidence) if gav_evidence else 'Débil o no detectada'} |\n\n"
"### Respuestas visuales clave\n\n"
"1. **¿El rendimiento cae después de una ventana T8?**  \n"
"   {'Sí, en promedio' if worst_delta < -5 else 'No de forma significativa'}: \"\n"
"   f\"{worst_a} cae {abs(worst_delta):.1f}% en promedio post-ventana.\n\n"
"2. **¿Cuánto cae?**  \n"
"   Peor evento: **{worst['activo']}** el **{worst['ini']}** con **{worst['delta_pct']:.1f}%** de caída.\n\n"
"3. **¿Qué molino se afecta más?**  \n"
"   **{worst_a}** con Δ promedio de **{worst_delta:.1f}%**.\n\n"
"4. **¿Cuánto demora en recuperarse?**  \n"
"   **{slow_a}** tarda en promedio **{slow_h:.1f} horas** en recuperar el 90% del baseline.\n\n"
"5. **¿Se observa efecto gaviota?**  \n"
"   {'Sí — ' + '; '.join(gav_evidence) + '.' if gav_evidence else 'Efecto débil o variable entre eventos.'}\n\n"
"### Recomendación operacional\n\n"
"- Priorizar monitoreo de **{worst_a}** durante y post-ventana T8.\n"
"- Activar protocolo de compensación si la ventana supera **4 horas** acumuladas.\n"
"- Revisar nivel de pila de alimentación antes de cada ventana programada.\n"
"- Planificar ventanas cortas (<2h) cuando la pila esté por debajo del 60%.\n"
"'''\n"
"    return md_text\n\n"
"resumen_md = build_executive_summary(df_met, resumen_activo, gaviota_data, eventos_t8)\n"
"ipy_display(Markdown(resumen_md))\n\n"
"# Guardar\n"
"with open(OUT_RPT/'monitoreo_efecto_gaviota.md','w',encoding='utf-8') as f:\n"
"    f.write(resumen_md)\n"
"print('Resumen guardado: outputs/reports/monitoreo_efecto_gaviota.md')"
)

# ─── Ensamblar las celdas nuevas ─────────────────────────────────────────────
NUEVAS_CELDAS = [
    md("---\n## 8b. Monitoreo Visual Pre/Post — Efecto Gaviota\n\n"
       "> **Objetivo:** visualizar el patrón *estable → caída → recuperación* "
       "en los rendimientos de molienda antes, durante y después de cada ventana Teniente 8.\n\n"
       "```\n"
       "rendimiento estable (pre)\n"
       "    ↓  caída durante o después de la ventana T8\n"
       "    ↑  recuperación posterior\n"
       "```\n\n"
       "**Parámetros:** PRE_HOURS=24h | POST_HOURS=24h | Rolling MA=1h"),
    C_SKILLS,
    C_FUNCS,
    md("### 8b.1 Detección de eventos y métricas"),
    C_EVENTS,
    md("### 8b.2 Series temporales por evento (top impacto)"),
    C_PLOT_EV,
    md("### 8b.3 Efecto Gaviota agregado — TPH normalizado"),
    C_GAVIOTA,
    md("### 8b.4 Ranking de impacto y recuperación"),
    C_RANK,
    md("### 8b.5 Exportación y resumen ejecutivo"),
    C_EXPORT,
    C_SUMMARY,
]

# ─── Insertar en el notebook ──────────────────────────────────────────────────
nb = json.loads(NB.read_text(encoding='utf-8'))

# Posición de inserción: después de celda 21 (tiempos recuperación)
INSERT_AFTER = 21

new_cells = nb['cells'][:INSERT_AFTER+1] + NUEVAS_CELDAS + nb['cells'][INSERT_AFTER+1:]
nb['cells'] = new_cells

NB.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding='utf-8')

code_cells = sum(1 for c in nb['cells'] if c['cell_type']=='code')
md_cells   = sum(1 for c in nb['cells'] if c['cell_type']=='markdown')
n_cells = len(nb['cells'])
print(f'OK notebook actualizado: {n_cells} celdas ({code_cells} code + {md_cells} markdown)')
print(f'Seccion gaviota: {len(NUEVAS_CELDAS)} celdas nuevas insertadas en posicion {INSERT_AFTER+1}')
